### ISSUE TITLE
Minor Nitpick ;)

### ISSUE THREAD

**Issue by idibidiart** [mpdairy/posh#1]
"Because it uses a single app state like Om or re-frame"

I guess "single app state" could mean that the program does nothing after rendering initial state. What I believe you mean is "single state store"

**Comment by idibidiart** [comment]
Awesome idea btw. Been waiting for this.

**Comment by mpdairy** [comment]
Oh, right, that type of single app state would be rather limiting... I changed it to "Because it uses a single database to store app state"
