### ISSUE TITLE
Error attempting to use pull expression 

### ISSUE THREAD

**Issue by handojin** [mpdairy/posh#5]
(p/pull conn '[*] 1)

works fine on initial page load and on page re-renders after a new value has been transacted

(p/pull conn '[\* {:some/attribute [*]] 1)

where :some/attribute is a :db.type/ref attribute (non-component)

works fine on initial load but fails on rerender after a new value has been transacted:

Uncaught Error: _ is not ISeqable

**Comment by mpdairy** [comment]
Thanks, I'll take a look. I'm about to update to a new pattern matching / generation system so maybe now's a good day to switch it over.

**Comment by handojin** [comment]
Thx. I'll keep an eye out for the change and retry once it's applied. FWIW, I'm able to hack around this by using posh to run a simple query returning a change (last tx) and making my pull statement a regular datascript pull. Not sure it's a great idea long term.

Nice lib btw!

**Comment by mpdairy** [comment]
You should also be able to use `pull-tx` instead of `pull` with a tx-pattern `'[[]]` and it ought to update every time.

**Comment by handojin** [comment]
Confirmed that works. Thanks!

**Comment by mpdairy** [comment]
Ok can you try using Posh 0.3.5 and switch back to just using `pull` instead of `pull-tx` and see if it works? The new pattern matching I added to `pull` is (hopefully) exact and pulls always and only when a tx datom will change the pull's result.

**Comment by handojin** [comment]
No regressions on the use of pull-tx and the new pull, it works! Thanks much. I'm using this in combo w/ re-frame/re-com. That and the datascript / posh combo is the dog's bollocks.
