### ISSUE TITLE
Demo Google malware warning

### ISSUE THREAD

**Issue by ghost** [mpdairy/posh#9]
Not sure what 'trashy' in the trashy demo is supposed to mean exactly, but my first guess would be to presume it is trashable as in the sense that people can input all kinds of test/demo/trial-and-error data to the demo.

Seems someone has taken it a step beyond that and actually managed to get in?

![image](https://cloud.githubusercontent.com/assets/11848802/16745554/a2786ff8-47b6-11e6-9206-07c4e7ac8e9e.png)

Well that or the host just is compromised.... you may wish to check that out.

**Comment by mpdairy** [comment]
Yeah it's just my wordpress site that got hacked, nothing to do with the live demo.  I'm in the process of moving everything to a fresh server so it should be fixed soon.

**Comment by ghost** [comment]
Fine with me, just making sure you were aware of it in the first place :) Cheers and GL
